### ISSUE TITLE
option to add generated classes to sources

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/contraect-maven-plugin#13]
it would be great to automatically add the generated classes to the source-folder. otherwise it is required to do that either manually or use another plugin (e.g. build-helper-maven-plugin) to do that job.

article about that topic here:
- https://blog.soebes.de/blog/2016/06/11/maven-anti-patterns-build-helper-maven-plugin/

**Comment by mitch-lbw** [comment]
please validate the maven configuration parameter "targetPath"

**Comment by marc0olo** [comment]
this is definitely one option to get the desired result. maybe we should give that issue a low priority. I personally always try to avoid putting generated classes in the regular source folder. IMO they shouldn't be committed and pushed into the repo.

**Comment by marc0olo** [comment]
if possible it would be nice to have an additional config-param `addToSources` which does what the following plugin does:
```
<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.build.directory}/generated-sources/contraect</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by mitch-lbw** [comment]
> if possible it would be nice to have an additional config-param `addToSources` which does what the following plugin does:
> 
> ```
> <plugin>
>         <groupId>org.codehaus.mojo</groupId>
>         <artifactId>build-helper-maven-plugin</artifactId>
>         <version>3.0.0</version>
>         <executions>
>           <execution>
>             <phase>generate-sources</phase>
>             <goals>
>               <goal>add-source</goal>
>             </goals>
>             <configuration>
>               <sources>
>                 <source>${project.build.directory}/generated-sources/contraect</source>
>               </sources>
>             </configuration>
>           </execution>
>         </executions>
>       </plugin>
> ```

This should be added to the documentation because it's up to the user of the plugin how to handle the generated classes

**Comment by marc0olo** [comment]
this is already included in the documentation, see https://kryptokrauts.gitbook.io/contraect-maven-plugin/use-the-plugin/plugin-execution#add-generated-classes-to-sources

**Comment by mitch-lbw** [comment]
@marc0olo any open issues here?

**Comment by marc0olo** [comment]
closing this for now. maybe we can include this logic into our plugin at a later point of time.
