### ISSUE TITLE
Check contract bytecode for given contractId

### ISSUE THREAD

**Issue by mitch-lbw** [kryptokrauts/contraect-maven-plugin#2]
currently the node does not support retrieving the complete bytecode from a deployed contract - this is needed to check if the deployed bytecode is the same like the generated contract
the code already exists, but we need to wait until the PRs are release
https://github.com/aeternity/aesophia/pull/173
https://github.com/aeternity/aesophia_cli/pull/27
https://github.com/aeternity/aesophia_http/pull/49

**Comment by mitch-lbw** [comment]
Check new endpoint defined in #49

**Comment by marc0olo** [comment]
this should be possible from version 4.1.0 on according to the release notes:
- https://github.com/aeternity/aesophia_http/releases

**Comment by mitch-lbw** [comment]
introduced a new switch "checkBytecode" which defaults to false - if true, the bytecode will be checked.
ATM this is commented out, because the bytcodes compiled and delivered through node differ

**Comment by marc0olo** [comment]
when running the node with network `local_iris_testnet` we should be able to check the bytecode now if we test against the recent version of the node

**Comment by marc0olo** [comment]
We need to create an image for current release candidate (https://forum.aeternity.com/t/iris-release-candidate/9239) and verify whether this is working now. Otherwise we need to comment the forum thread to check if we are doing sth. wrong or why this is still not working.

**Comment by marc0olo** [comment]
tested and works
