### ISSUE TITLE
evaluate impact of including other contracts

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/contraect-maven-plugin#20]
we need to consider that it is possible to include built-in contracts like `List.aes`. we need to verify the impact to our generated classes and add support for this if necessary.

the contracts can e.g. contain:
```
include "List.aes"
```

**Comment by marc0olo** [comment]
examples can be found in the "Advent of Code" repository of Hans:
- https://github.com/hanssv/AoC2019

**Comment by marc0olo** [comment]
more information about that topic here:
- https://github.com/aeternity/protocol/blob/master/contracts/sophia_stdlib.md#standard-library

**Comment by marc0olo** [comment]
as discussed we probably need to also consider the includes. at least we need to verify the impact regarding bytecode when using imports.

it is also possible to define custom includes. example here:
- https://github.com/hanssv/AoC2019/tree/master/11

more about that here:
- https://github.com/aeternity/protocol/blob/master/contracts/sophia.md#splitting-code-over-multiple-files

**Comment by marc0olo** [comment]
@mitch-lbw I think we should check this one here before the release. I would like to make sure we do not miss anything here before releasing v1.0.0

**Comment by marc0olo** [comment]
as discussed we don't expect any problems by using built-in imports.

currently it isn't possible to compile contracts that use custom imports (which are referenced on the filesystem).

for the compiler it is possible to provide the attributes `srcFile` and `fileSystem`. we need to figure out how these attributes must be filled and what changes need to be implemented in order to support this.

maybe we should skip that for now and make a release `v0.9.2` with the current state and wait with `v1.0.0` until this is working. what do you think @mitch-lbw ?

**Comment by marc0olo** [comment]
further discussion here:
- https://forum.aeternity.com/t/compilation-of-contract-with-include/6285/7

**Comment by mitch-lbw** [comment]
Discussion on deployment of contracts with includes
* https://forum.aeternity.com/t/deployment-of-contracts-with-custom-library-500-internal-server-errors/6381/3

**Comment by marc0olo** [comment]
![image](https://user-images.githubusercontent.com/8124114/76165681-2b05b780-6159-11ea-90c5-2abdd142e2ea.png)

**Comment by marc0olo** [comment]
works now
