### ISSUE TITLE
handle payable modifier (aettos as param in generated methods)

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/contraect-maven-plugin#27]
if a method is declared with the `payable` modifier it must be possible to provide an amount of aettos to the method.

currently it isn't possible to send an amount of aettos in the generated methods.

**example**
- the `payAndSplit` method in our `PaymentSplitter` contract

**Comment by mitch-lbw** [comment]
fixed with 37315a5f81b5fbaa9e3adea23bf352e107d627d8
