### ISSUE TITLE
make bytecode check optional

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/contraect-maven-plugin#28]
by default a bytecode check shouldn't be executed when initializing a contract-instance. this needs to be optional.

for example we generate the java class from a contract-interface and want to use this for multiple contracts that could all have a different bytecode

**Comment by mitch-lbw** [comment]
introduced a new switch "checkBytecode" which defaults to false - if true, the bytecode will be checked.
ATM this is commented out, because the bytcodes compiled and delivered through node differ
