### ISSUE TITLE
include some cool ASCII in the header of the generated classes?

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/contraect-maven-plugin#30]
maybe we can add some information about kryptokrauts in the header of each class. we should also point to https://kryptokrauts.com/support and to the documentation of the plugin https://kryptokrauts.gitbook.io/contraect-maven-plugin/

what about an ASCII? e.g.:

```
 _                         _          _                        _        
| |                       | |        | |                      | |       
| | __ _ __  _   _  _ __  | |_  ___  | | __ _ __  __ _  _   _ | |_  ___ 
| |/ /| '__|| | | || '_ \ | __|/ _ \ | |/ /| '__|/ _` || | | || __|/ __|
|   < | |   | |_| || |_) || |_| (_) ||   < | |  | (_| || |_| || |_ \__ \
|_|\_\|_|    \__, || .__/  \__|\___/ |_|\_\|_|   \__,_| \__,_| \__||___/
              __/ || |                                                  
             |___/ |_|        
```

**Comment by mitch-lbw** [comment]
sample 
![image](https://user-images.githubusercontent.com/9591055/75293826-50c0c180-5827-11ea-84f4-27aff9ede61f.png)

**Comment by marc0olo** [comment]
@mitch-lbw we should also add a disclaimer!
