### ISSUE TITLE
Add possibility to provide tx-options (fee, nonce, ...)

### ISSUE THREAD

**Issue by mitch-lbw** [kryptokrauts/contraect-maven-plugin#38]
Currently the fee is always calculated - every method should provide an optional parameter to set the fee for the call manually

**Comment by marc0olo** [comment]
we shouldn't limit this to fee only. it's good to have a convenience method for contract deployments and calls. but the devs should in best case be able to set a custom value for every property

**Comment by marc0olo** [comment]
I think we can close this. should be covered with #64 as we introduced a `ContractTxOptions` class in the SDK now for the convenience methods
