### ISSUE TITLE
Remove fixed gas limit from dryRun and make configurable via maven config

### ISSUE THREAD

**Issue by mitch-lbw** [kryptokrauts/contraect-maven-plugin#58]
within `buildDeployContractMethod` the gas is set fixed to 48000000l
reset by resolving value from maven config, defaulting to 50k

**Comment by marc0olo** [comment]
@mitch-lbw this would also be important for all other entrypoints. not sure if it is only considered for deployment right now

**Comment by marc0olo** [comment]
here I was discussing about an `ContractTxOptions` object that could be passed and consumed: https://github.com/kryptokrauts/contraect-maven-plugin/issues/64
