### ISSUE TITLE
PayingForTx: `ContractCreateTx` and `ContractCallTx` as inner transaction

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/contraect-maven-plugin#61]
@mitch-lbw we need to think about how we want to provide that functionality using methods of the contract-maven-plugin.

I think we should be able provide an `options` object to each contract method (including deploy) that has at least these two attributes:
- `amount` (BigInteger)
- `innerTx` (Boolean)

**Comment by mitch-lbw** [comment]
Edge case - probably no use cases feasible. We won't work on that until somebody needs the functionality and has a feasible use case.
